name: Create Release

on:
  workflow_run:
    workflows: ["Build and Upload Artifacts"]
    types: [completed]

jobs:
  release:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DEBUG — Info evento e run
        run: |
          echo "Workflow triggering this run:"
          echo "Workflow name: ${{ github.event.workflow.name }}"
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"

      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          name: release_artifacts
          path: release_artifacts
          run-id: '${{ github.event.workflow_run.id }}'

      - name: Debug — lista file scaricati
        shell: bash
        run: |
          echo "Contenuto scaricato:"
          find release_artifacts || echo "Nessun file trovato"

      - name: Estrai versione da Cargo.toml
        id: extract_version
        run: |
          VERSION=$(grep '^version' Cargo.toml | head -n1 | cut -d '"' -f2)
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Crea GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.extract_version.outputs.version }}
          name: "v${{ steps.extract_version.outputs.version }}"
          body_path: CHANGELOG.md
          files: |
            release_artifacts/rfortune-*
            release_artifacts/*.sig
            release_artifacts/*.sha256
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cleanup
        if: always()
        run: rm -rf release_artifacts
